# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0010_userhealthrecord_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthrecord',
            name='Painkiller',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
