# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0008_auto_20160630_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealthrecord',
            name='AF',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='userhealthrecord',
            name='Asthma',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='userhealthrecord',
            name='DM',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='userhealthrecord',
            name='DysLip',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='userhealthrecord',
            name='HF',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='userhealthrecord',
            name='HT',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='userhealthrecord',
            name='Stroke',
            field=models.CharField(max_length=1),
        ),
    ]
