# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userHealthRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Age', models.SmallIntegerField()),
                ('HT', models.BooleanField(default=0)),
                ('DM', models.BooleanField(default=0)),
                ('DysLip', models.BooleanField(default=0)),
                ('Asthma', models.BooleanField(default=0)),
                ('HF', models.BooleanField(default=0)),
                ('Stroke', models.BooleanField(default=0)),
                ('AF', models.BooleanField(default=0)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('endLoginDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
