# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0003_auto_20160630_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealthrecord',
            name='Gender',
            field=models.CharField(max_length=4),
        ),
    ]
