# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0013_auto_20160826_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minTemp', models.SmallIntegerField()),
                ('maxTemp', models.SmallIntegerField()),
                ('weather', models.CharField(max_length=20)),
                ('minPM25', models.PositiveSmallIntegerField()),
                ('maxPM25', models.PositiveSmallIntegerField()),
                ('suggestion', models.CharField(max_length=80)),
            ],
        ),
    ]
