# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-17 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0014_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='age',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suggestions',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
